spring.application.name=callahan-codigo-fuente
spring.datasource.url=jdbc:h2:./db/basedatos;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.key=0f2eae67684d3c0435bff8f0c6e847f3